FROM rust:1.86.0

RUN apt-get update && apt-get install -y \
    git \
    make \
    shellcheck \
    && rm -rf /var/lib/apt/lists/*

# Install development tools
RUN cargo install just cargo-deny cargo-semver-checks typos-cli
